FROM node

# add work dir
RUN mkdir -p /app
WORKDIR /app

# copy dependncy
COPY package.json . 
RUN npm install 

# copy app files 

COPY . .

# host 
EXPOSE 5000

# start app

CMD [ "node", "server.js" ] 